"""empty message

Revision ID: 9b4a940e9ff5
Revises: b11b3c7fad4f
Create Date: 2023-05-25 11:38:03.694103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b4a940e9ff5'
down_revision = 'b11b3c7fad4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
