"""empty message

Revision ID: b11b3c7fad4f
Revises: c1439a30b1c8
Create Date: 2023-05-24 12:52:57.381355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b11b3c7fad4f'
down_revision = 'c1439a30b1c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
