"""empty message

Revision ID: c1439a30b1c8
Revises: d0b409ad7411
Create Date: 2023-05-24 12:52:11.914720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1439a30b1c8'
down_revision = 'd0b409ad7411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
