"""empty message

Revision ID: c8d07f608876
Revises: a5c9649e244c
Create Date: 2023-05-25 16:18:28.522486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d07f608876'
down_revision = 'a5c9649e244c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
